name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip source code
        run: zip -r some_web.zip . -x '*.git*'

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exact-timestamps
        env:
          AWS_S3_BUCKET: azizbekproect
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: your-region
          SOURCE_DIR: "."
          DEST_DIR: "app"

      - name: Deploy via CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: some_web
          deployment-group: test-blog
          deployment-config: CodeDeployDefault.AllAtOnce
          description: 'Automated deployment'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
